### ISSUE TITLE
UI Entwurf

### ISSUE THREAD

**Issue by cidsCustomizer** [helllth/cids-custom-dev-tutorial-client#4]
in diesem Issue wird der Entwurf des Geocaching Renderer und die Struktur des Baums dokumentiert:

**Comment by helllth** [comment]
Mockup:

![bildschirmfoto 2016-06-22 um 17 45 10](https://cloud.githubusercontent.com/assets/837211/16273257/320bad1c-38a1-11e6-83b0-b15593733281.png)

**Comment by helllth** [comment]
### Struktur des Baumes:

#### Nach Schwierigkeitsgrad
- 1.0
  - H 100
  - ...
- 1.5
  - Friedhöfe in Wuppertal #4
- 2.0
- 2.5
- 3.0
  - Schäbiger Diktator
- 3.5
- 4.0
- 4.5
- 5.0
